files = {
    0: maps\5_units.txt,
    1: maps\5_units_vis1.txt,
    2: maps\6_units.txt,
    3: maps\6_units_b1.txt,
    4: maps\6_units_flip.txt,
    5: maps\6_units_vis1.txt,
    6: maps\big_alcoves.txt,
    7: maps\big_alcoves_vis1.txt,
    8: maps\binary_7x7.txt,
    9: maps\binary_7x7_rotated.txt,
    10: maps\corridors_to_three_tiny_rooms_with_alcoves.txt,
    11: maps\env17_a1.txt,
    12: maps\env17_b.txt,
    13: maps\env17_c.txt,
    14: maps\four_units.txt,
    15: maps\four_units_flip.txt,
    16: maps\four_units_vis1.txt,
    17: maps\test.txt,
    18: maps\test11.txt,
    19: maps\test21.txt,
    20: maps\tiny_rooms.txt,
}
